name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: npm install, build, and test
      run: |
        cd DotnetTemplate.Web
        npm install
        npm run build
    - name: dotnet TEST
      run: dotnet test
    - name: npm test
      run: |
        cd DotnetTemplate.Web
        npm t
    - name: npm run lint
      run: |
        cd DotnetTemplate.Web
        npm run lint
       